### ISSUE TITLE
create organization should accept a user

### ISSUE THREAD

**Issue by slively** [MVPStudio/soar#10]
`POST /organization/:organization_id?` should also accept user information and can create a user and organization in a single request
returns the new organization

**Comment by naheller** [comment]
```
POST /organization
{
   user: { ... }, // same as current new user object
   organization: { ... } // same as current new org object
}
```

**Comment by naheller** [comment]
create org in db, get id, put in user.orgRelations array as `{ orgId: ..., type: 'admin' }` and insert user into database.

**Comment by naheller** [comment]
see #17  for fields
