### ISSUE TITLE
when adding a tag to an org, check if it exists, create if needed in tags collection

### ISSUE THREAD

**Issue by slively** [MVPStudio/soar#13]

**Comment by Amcclennahan** [comment]
I'd actually like to use a list of predefined tags at first, to improve search and filter results. 

I'd also like to ask, here: when we say "tag," that could be any of the tags we've talked about, yeah? e.g. it could be a "mental health" tag that might be seen more like a category, but also tags like "fund raising" in a section that contains areas of expertise for an organization?

**Comment by slively** [comment]
That sounds good, and yeah a tag can be any word or phrase and an organization can have multiple tags
